# ????????? ??????????? ? Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=persondb
spring.datasource.password=password123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=persondb

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true